#!/bin/bash
# Builds the entire application from scratch
# All objects are deleted 

g++ -fopenmp -fomit-frame-pointer -fexpensive-optimizations -O3 -o gnu_parallel_partition.out -std=c++11 -march=corei7 -I /data/ext/boost_1_57_0/ -I /data/11.4/home/hyc/tbb/tbb43_20140724oss/include/  -L /data/11.4/home/hyc/tbb/tbb43_20140724oss/lib/intel64/gcc4.4/ -pthread -fopenmp -lpthread -ltbb -lrt gnu_parallel_partition.cpp
